import { jsPDF } from "jspdf";

export function exportPDF({ text, prediction, confidence, keywords }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = 0;

  const isFake = prediction === "Fake";
  const accentR = isFake ? 239 : 34;
  const accentG = isFake ? 68  : 197;
  const accentB = isFake ? 68  : 94;

  // ── Header bar ──
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 38, "F");

  // Logo circle
  doc.setFillColor(99, 102, 241);
  doc.circle(margin + 6, 19, 6, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FG", margin + 3.2, 21.5);

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("FakeGuard", margin + 16, 17);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("AI-Powered Fake News Detection Report", margin + 16, 24);

  // Timestamp top-right
  const now = new Date().toLocaleString();
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(now, W - margin, 24, { align: "right" });

  y = 50;

  // ── Verdict banner ──
  doc.setFillColor(accentR, accentG, accentB);
  doc.roundedRect(margin, y, contentW, 22, 4, 4, "F");

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  const verdictText = isFake ? "🚨  FAKE NEWS DETECTED" : "✅  REAL NEWS";
  doc.text(verdictText, W / 2, y + 9, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Confidence Score: ${confidence}%`, W / 2, y + 17, { align: "center" });

  y += 32;

  // ── Confidence bar ──
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(margin, y, contentW, 6, 3, 3, "F");
  const fillW = (confidence / 100) * contentW;
  doc.setFillColor(accentR, accentG, accentB);
  doc.roundedRect(margin, y, fillW, 6, 3, 3, "F");

  y += 16;

  // ── Model info row ──
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, contentW, 14, 3, 3, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(99, 102, 241);
  doc.text("Model:", margin + 4, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 41, 59);
  doc.text("Stacking Ensemble (LR + SVM + RF + XGBoost)", margin + 20, y + 6);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(99, 102, 241);
  doc.text("Accuracy:", margin + 4, y + 11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 41, 59);
  doc.text("98.9% on test set (8,984 samples)", margin + 24, y + 11);

  y += 24;

  // ── Keywords ──
  if (keywords?.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("TOP TRIGGERING KEYWORDS", margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    let x = margin;
    const tagH = 7;
    const tagPad = 3;

    keywords.forEach((k) => {
      const tw = doc.getTextWidth(k.word) + tagPad * 2 + 2;
      if (x + tw > W - margin) { x = margin; y += tagH + 3; }
      doc.setFillColor(238, 242, 255);
      doc.setDrawColor(199, 210, 254);
      doc.roundedRect(x, y, tw, tagH, 2, 2, "FD");
      doc.setTextColor(79, 70, 229);
      doc.text(k.word, x + tagPad, y + 5);
      x += tw + 3;
    });
    y += tagH + 12;
  }

  // ── Divider ──
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(margin, y, W - margin, y);
  y += 8;

  // ── Article text ──
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text("ANALYZED ARTICLE", margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);

  const lines = doc.splitTextToSize(text, contentW);
  const maxLines = 55;
  const displayLines = lines.slice(0, maxLines);
  if (lines.length > maxLines) displayLines.push("... [truncated]");

  displayLines.forEach((line) => {
    if (y > 272) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 5;
  });

  // ── Footer ──
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 284, W, 13, "F");
    doc.setDrawColor(226, 232, 240);
    doc.line(0, 284, W, 284);
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by FakeGuard — AI Fake News Detector", margin, 291);
    doc.text(`Page ${i} of ${pageCount}`, W - margin, 291, { align: "right" });
  }

  const filename = `fakeguard-report-${Date.now()}.pdf`;
  doc.save(filename);
}
